[package]
name = "penforge"
version = "0.1.0"
description = "PenForge — Penetration Testing Report Manager"
authors = ["Perchant"]
edition = "2021"

[lib]
name = "penforge_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "penforge"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri              = { version = "2", features = [] }
tauri-plugin-fs     = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell  = "2"
serde              = { version = "1", features = ["derive"] }
serde_json         = "1"
bcrypt             = "0.15"
anyhow             = "1"
uuid               = { version = "1", features = ["v4"] }
chrono             = { version = "0.4", features = ["serde"] }
